name: GitHub Pages

on:
  push:
    branches:
      - master
      - main
    paths:
      - "src/**"
      - "example/**"
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build example
        run: pnpm build:example

      - name: Add .nojekyll file
        run: touch ./demo/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo
          force_orphan: true
